"""Changed foreign key of referral_id in users_referral_codes

Revision ID: 549c9fc6d7cc
Revises: 1a9c8ec1d5c2
Create Date: 2024-02-06 18:11:26.304352

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "549c9fc6d7cc"
down_revision: Union[str, None] = "1a9c8ec1d5c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_referral_codes_referral_id_fkey",
        "user_referral_codes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_referral_codes",
        "users",
        ["referral_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_referral_codes", type_="foreignkey")
    op.create_foreign_key(
        "user_referral_codes_referral_id_fkey",
        "user_referral_codes",
        "referral_codes",
        ["referral_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
