"""Changed user_id in referral code

Revision ID: 78e41b108d29
Revises: 69eebf7f67ab
Create Date: 2024-02-06 13:55:49.374674

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "78e41b108d29"
down_revision: Union[str, None] = "69eebf7f67ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "referral_codes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "referral_codes", type_="foreignkey")
    # ### end Alembic commands ###
